name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit and Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update CHANGELOG
          title: 'Update CHANGELOG for ${{ github.event.release.name }}'
          body: |
            This PR updates the CHANGELOG with the release notes from ${{ github.event.release.name }}.
          branch: changelog/update-${{ github.event.release.name }}
          base: main
          add-paths: |
            CHANGELOG.md
